inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/schema.rb
    - 'vendor/**/*'

Style/TrailingCommaInLiteral:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes